### PR TITLE
Fix for rust 1.80

### LINKED ISSUE #13: mpris-notifier build failed
```
error[E0282]: type annotations needed for `Box<_>`
  --> /build/mpris-notifier-0.1.7-vendor.tar.gz/time/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

   Compiling tiff v0.9.0
For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: builder for '/nix/store/fjc87vz6rr0bl80fq6163jiljfz71rfx-mpris-notifier-0.1.7.drv' failed with exit code 101
error: 1 dependencies of derivation '/nix/store/qc5j2k6lqj97681dn1lxfn02fr2drrbh-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/z0k3sxiiknm9zicslzivw3wb033x006f-nixos-system-nixos-24.11pre668759.8a3354191c0d.drv' failed to build
```
This is the error i get when trying doing `sudo nixos-rebuild switch`

### PR DESCRIPTION
**Pull request by Leixb**
Older versions of the `time` crate do not compile in the newest rust 1.80. 

fixes #13

### CODE REVIEW

**Comment by l1na-forever** [comment]
Hey Leix, thanks so much for fixing this!
